sonar.projectKey=alexsandroocanha_Golang-Api-Crud
sonar.organization=alexsandroocanha
sonar.sources=.
sonar.exclusions=**/*_test.go,**/mocks/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
